# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MoGUpQs_E7CqTt7T2OQxXgPXz8RssUDW
"""

import streamlit as st
import pandas as pd
import joblib


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Admission Success Predictor",
    page_icon="🎓",
    layout="centered"
)


# ============================================================
# LOAD MODEL
# ============================================================

model = joblib.load("admission_prediction_model.pkl")


# ============================================================
# TITLE
# ============================================================

st.title("🎓 Admission Success Predictor")

st.write(
    """
    Enter an applicant's academic and application profile
    to estimate their admission outcome.
    """
)

st.info(
    "This model is a portfolio machine-learning project and "
    "should be treated as a predictive aid, not an official "
    "admission decision."
)


# ============================================================
# INPUT SECTION
# ============================================================

st.subheader("Applicant Profile")


col1, col2 = st.columns(2)


with col1:

    gre_score = st.number_input(
        "GRE Score",
        min_value=260,
        max_value=340,
        value=320,
        step=1
    )

    toefl_score = st.number_input(
        "TOEFL Score",
        min_value=0,
        max_value=120,
        value=110,
        step=1
    )

    university_rating = st.selectbox(
        "University Rating",
        options=[1, 2, 3, 4, 5],
        index=3
    )

    sop = st.slider(
        "Statement of Purpose (SOP)",
        min_value=1.0,
        max_value=5.0,
        value=4.0,
        step=0.5
    )


with col2:

    lor = st.slider(
        "Letter of Recommendation (LOR)",
        min_value=1.0,
        max_value=5.0,
        value=4.0,
        step=0.5
    )

    cgpa = st.number_input(
        "CGPA",
        min_value=0.0,
        max_value=10.0,
        value=9.0,
        step=0.01
    )

    research = st.selectbox(
        "Research Experience",
        options=["No", "Yes"]
    )


# ============================================================
# CONVERT RESEARCH TO MODEL FORMAT
# ============================================================

research_value = 1 if research == "Yes" else 0


# ============================================================
# CREATE INPUT DATAFRAME
# ============================================================

input_data = pd.DataFrame({
    "GRE Score": [gre_score],
    "TOEFL Score": [toefl_score],
    "University Rating": [university_rating],
    "SOP": [sop],
    "LOR": [lor],
    "CGPA": [cgpa],
    "Research": [research_value]
})


# ============================================================
# PREDICTION
# ============================================================

if st.button("🔍 Predict Admission", use_container_width=True):

    prediction = model.predict(input_data)[0]

    probability = model.predict_proba(input_data)[0][1]

    st.divider()

    st.subheader("Prediction Result")


    if prediction == 1:

        st.success("🎓 Predicted Outcome: ADMITTED")

    else:

        st.error("❌ Predicted Outcome: REJECTED")


    st.metric(
        label="Estimated Admission Probability",
        value=f"{probability:.2%}"
    )


    # ========================================================
    # PROBABILITY BAR
    # ========================================================

    st.progress(float(probability))


    # ========================================================
    # SHOW INPUT PROFILE
    # ========================================================

    with st.expander("View Applicant Profile"):

        st.dataframe(
            input_data,
            use_container_width=True
        )


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    "Admission Success Predictor | Machine Learning Portfolio Project"
)